// Las rutas van ser renderizadas en "children"

import { Navigation } from "../components/Navigation" // Importamos otro componente
import '../src/styles/globals.css' // Importamos los estilos globales

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <head>
        <title>Next 13 APP</title>
      </head>
      
      <body>
         <Navigation/>
        {children}
        </body>
    </html>
  )
}
